CREATE TABLE IF NOT EXISTS items (
    id PRIMARY KEY AUTO_INCREMENT,
    `name` varchar(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO items (`name`) VALUES ("An example item!");